<?php

namespace QuoteCMS\PostBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostPictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostPictureRepository extends EntityRepository
{
}
