<?php

namespace QuoteCMS\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShareCountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShareCountRepository extends EntityRepository
{
}
