<?php

namespace QuoteCMS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AvatarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvatarRepository extends EntityRepository
{
}
