<?php

namespace QuoteCMS\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
  public function getArtcleQueryByCatSlug($slug)
  {
    // May be a problem with many to many ! will see :o
    $query = $this->_em->createQuery("SELECT a, c
                                      FROM QuoteCMSBlogeBundle:Article a
                                      JOIN a.categories c
                                      WHERE c.slug = :categorySlug
                                      ORDER BY a.creationDate DESC");

   $query->useQueryCache(true);
   $query->useResultCache(true, 300);

   return $query;
  }
}
