<?php

namespace Silentkernel\CommentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends EntityRepository
{
    public function getCommentCount($context, $contextId)
    {
        $query = $this->_em->createQuery("SELECT COUNT(c) as commentCount
        FROM SilentkernelCommentBundle:Topic t
        JOIN t.comments c
        WHERE t.context = :context
        AND t.contextId = :contextId
        AND c. validated = true");

        $query->setParameter(":context", $context);
        $query->setParameter(":contextId", $contextId);

        $query->useQueryCache(true);
        $query->useResultCache(true, 120);

        $result = $query->getArrayResult();

        if (isset($result[0]["commentCount"]))
            return $result[0]["commentCount"];
        else
            return 0;
    }
}
